package:
  name: ncurses
  version: "6.0"

source:
  fn: ncurses-6.0.tar.gz
  url: ftp://ftp.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz 
  md5: ee13d052e1ead260d7c28071f46eefb1

build:
  number: 4
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc
  run:
    - libgcc

about:
  home: http://www.gnu.org/software/ncurses/
  license:  Free software (X11 License)

