package:
  name: micawber
  version: "0.3.3"

source:
  fn: micawber-0.3.3.tar.gz
  url: https://pypi.python.org/packages/source/m/micawber/micawber-0.3.3.tar.gz
  md5: a6ba38745267618c091e8a8b4854a535
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - micawber = micawber:main
    #
    # Would create an entry point called micawber that calls micawber.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - django
    - examples
    - examples.django_ex
    - micawber
    - micawber.contrib
    - micawber.contrib.mcdjango
    - micawber.contrib.mcdjango.mcdjango_tests
    - micawber.contrib.mcdjango.templatetags

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/coleifer/micawber/
  license: MIT License
  summary: 'a small library for extracting rich content from urls'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
