package:
  name: gdk-pixbuf
  version: "2.30.8"

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/gdk-pixbuf/2.30/gdk-pixbuf-2.30.8.tar.xz 
  fn: gdk-pixbuf-2.30.8.tar.xz

build:
  number: 3
  detect_binary_files_with_prefix: true

requirements:
  build:
    # - gcc
    - python ==2.7.10
    - m4
    - autoconf
    - automake
    - libtool
    - pkg-config
    - system
    - glib
    - gobject-introspection
    - libffi
    - libtiff
    - libpng
  run:
    - system
    - glib
    - gobject-introspection
    - libffi
    - libtiff
    - libpng

about:
  home: https://developer.gnome.org/gdk-pixbuf/ 
  summary: "The GdkPixbuf Structure — Information that describes an image."

