{% set major_version = "3.21" %}
{% set minor_version = "0" %}
{% set version = major_version + "." + minor_version %}

package:
  name: pygobject
  version: {{ version }}

source:
  fn: pygobject-{{ version }}.tar.xz 
  url: http://ftp.gnome.org/pub/GNOME/sources/pygobject/{{ major_version }}/pygobject-{{ version }}.tar.xz 
  md5: a6dba83e3a7df52ba80bd02906f74611 

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m4
    - autoconf
    - automake
    - pkg-config
    - libtool
    - python
    - gnome-common
    - glib >=2.43
    - gobject-introspection
    - gettext
    - cairo
    - cairo-gobject
    - pycairo
    - libsigcpp
    - gtk
    - pango
    - libffi
  run:
    - libgcc
    - python
    - gnome-common
    - glib >=2.43
    - gobject-introspection 
    - gettext
    - cairo
    - cairo-gobject
    - pycairo
    - libsigcpp
    - gtk
    - pango
    - libffi

test:
  imports:
    - gi
    - gi.repository
    - gi.repository.GObject
    - gi.repository.GLib
    - gi.repository.Gio
    - gi.repository.Gtk

about:
  home: https://wiki.gnome.org/Projects/PyGObject 
  license: "LGPL 2.1"
  summary: "PyGObject is a Python extension module that gives clean and consistent access to the entire GNOME software platform through the use of GObject Introspection."

