{% set version = "5.3.1" %}

package:
  name: pypy
  version: {{ version }}

build:
  number: 0 

source:
  fn: pypy-{{ version }}-linux_x86_64-portable.tar.bz2
  url: https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-{{ version }}-linux_x86_64-portable.tar.bz2 
  md5: d29535d27fc09afa20c2c9c22e113dba

requirements:
  run:
    - openssl
    - sqlite
    - system
    - tk
    - zlib
    - bzip2
    - libffi
    - expat
    - ncurses

test:
  commands:
    - pypy --help

about:
  home: http://pypy.org/ 
  license: MIT
  summary: PyPy is a Python interpreter and just-in-time compiler.

