package:
  name: icu
  version: 56.1

build:
  number: 2
 
source:
  fn: icu4c-56_1-src.tgz
  url: http://download.icu-project.org/files/icu4c/56.1/icu4c-56_1-src.tgz 
  md5: c4a2d71ff56aec5ebfab2a3f059be99d

requirements:
  build:
    - gcc
  run:
    - libgcc

about:
  home: http://site.icu-project.org/
  license: MIT

