package:
  name: sparsehash
  version: 2.0.2

source:
  fn: sparsehash-2.0.2.tar
  url: https://sparsehash.googlecode.com/files/sparsehash-2.0.2.tar.gz
  md5: 1db92ed7f257d9b5f14a309d75e8a1d4

requirements:
  build:
    - gcc
    
  run:
    - libgcc
  
about:
  summary: 'An extremely memory-efficient hash_map implementation'
