{% set version = "1.14.2" %}

package:
  name: cairo
  version: {{ version }}

source:
  url: http://cairographics.org/releases/cairo-{{ version }}.tar.xz 
  fn: cairo-{{ version }}.tar.xz
  md5: e1cdfaf1c6c995c4d4c54e07215b0118

build:
  number: 3

requirements:
  build:
    - m4
    - autoconf
    - automake
    - libtool
    - pkg-config
    - boost
    - mm-common
    - libsigcpp
    - freetype
    - pixman ==0.32.6
    - libpng
    - zlib
    - glib
    - gobject-introspection
    - fontconfig
    - libxcb
  run:
    - boost
    - mm-common
    - libsigcpp
    - freetype
    - pixman ==0.32.6
    - libpng
    - zlib
    - glib
    - gobject-introspection
    - fontconfig
    - libxcb

about:
  home: http://cairographics.org/
  license: LGPL
  summary: "Cairo is a 2D graphics library with support for multiple output devices."

