package:
  name: pango
  version: "1.40.0"

source:
  fn: pango-1.40.0.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/pango/1.40/pango-1.40.0.tar.xz 
  sha256: da17985df314cb07d066ab5424f59c21ce973ece05b7de4df04d798ec8511c8b

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m4
    - autoconf
    - automake
    - libtool
    - pkg-config
    - gcc
    - python ==2.7.10
    - glib
    - gobject-introspection
    - libffi
    - cairo
    - harfbuzz
    - freetype
  run:
    - glib
    - gobject-introspection
    - libffi
    - cairo
    - harfbuzz
    - freetype

about:
  home: http://www.pango.org 
  summary: "Pango is a library for laying out and rendering of text, with an emphasis on internationalization. Pango can be used anywhere that text layout is needed, though most of the work on Pango so far has been done in the context of the GTK+ widget toolkit. Pango forms the core of text and font handling for GTK+-2.x."

