package:
  name: gobject-introspection 
  version: "1.44.0"

source:
  url: http://ftp.gnome.org/pub/gnome/sources/gobject-introspection/1.44/gobject-introspection-1.44.0.tar.xz 
  fn: gobject-introspection-1.44.0.tar.xz

build:
  number: 3
  detect_binary_files_with_prefix: true

requirements:
  build:
    - system
    - m4
    - autoconf
    - automake
    - libtool
    - pkg-config
    - python ==2.7.10
    - gcc
    - system
    - libffi >=3.0.0
    - glib ==2.44.1
    - zlib
    - flex
    - bison
  run:
    - system
    - libffi >=3.0.0
    - glib ==2.44.1
    - zlib
    - flex
    - bison

about:
  home: https://wiki.gnome.org/GObjectIntrospection/
  summary: "GObject introspection is a middleware layer between C libraries (using GObject) and language bindings. The C library can be scanned at compile time and generate a metadata file, in addition to the actual native C library. Then at runtime, language bindings can read this metadata and automatically provide bindings to call into the C library."

