package:
  name: libffi
  version: "3.2.1"

source:
  url: ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz 
  fn: libffi-3.2.1.tar.gz

build:
  number: 8
  rpaths:
    - lib/
    - lib64/

requirements:
  build:
    - system
    - m4
    - autoconf
    - automake
    - libtool
    - pkg-config
    - gcc
  run:
    - libgcc
    
about:
  home: https://sourceware.org/libffi/
  license: Liberal
  summary: "The libffi library provides a portable, high level programming interface to various calling conventions. This allows a programmer to call any function specified by a call interface description at run-time."

