package:
  name: expat
  version: 2.1.0

source: 
  fn: expat-2.1.0.tar.gz
  url: http://softlayer-dal.dl.sourceforge.net/project/expat/expat/2.1.0/expat-2.1.0.tar.gz

build:
  number: 0

requirements:
  build:
    - gcc

  run:
    - libgcc

about:
  home: 'http://expat.sourceforge.net/'
  summary: 'The Expat XML Parser'
