package:
  name: gettext
  version: 0.19.5

source:
  url: http://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.5.1.tar.gz 
  fn: gettext-0.19.5.1.tar.gz

build: 
  number: 2
 
requirements:
  build:
    - gcc
    - system
  run:
    - system
 
about:
  license: GNU
