package:
  name: pops
  version: "1.6.4"


source:
  fn: pops.tar.gz
  url: http://mathbio.nimr.mrc.ac.uk/download/POPS/pops.tar.gz
  md5: 599930636775f37bf78edb2d123adf53


build:
  number: 1


requirements:
  build:
    - gcc

  run:


test:
  requires: 
    - pops

  commands:
    - pops --help


about:
  home: http://mathbio.nimr.mrc.ac.uk/wiki/Software#POPS.2A
  license: GPL3
  summary: Fast and accurate computation of surface areas of proteins and nucleic acids.
