{% set version = "1.0.6" %}

package:
  name: bzip2
  version: {{ version }}

source:
  fn: bzip2-{{ version }}.tar.gz
  url: http://www.bzip.org/1.0.6/bzip2-{{ version }}.tar.gz 
  md5: 00b516f4704d4a7cb50a1d97e6e8e15b

build:
  number: 4

requirements:
  build:
    - gcc
  run:
    - libgcc

test:
  commands:
    - echo $(which bzip2)
    - bzip2 --help

about:
  home: https://github.com/ckolivas/lrzip 
  license: BSD-like
  summary: bzip2 and libbzip2. A program and library for data compression. 

