package:
  name: msms
  version: "2.6.1"

source:
  fn: msms_i86_64Linux2_2.6.1.tar.gz
  url: http://mgltools.scripps.edu/downloads/tars/releases/MSMSRELEASE/REL2.6.1/msms_i86_64Linux2_2.6.1.tar.gz
  md5: 650d8c6fd49d9ce291f30ed530d5f313

build:
  number: 3
  has_prefix_files:
    - bin/pdb_to_xyzr
    - bin/pdb_to_xyzrn

requirements:
  build:
    - gcc
  run:
    - libgcc

test:
  requires: 
    - msms
  commands:
    - msms -h

about:
  home: http://mgltools.scripps.edu/packages/MSMS/
  license: Free for academic use
  summary: MSMS is a program written in the C programming language to compute molecular surfaces. 
