package:
    name: blast
    version: 2.2.30

source:
  fn: ncbi-blast-2.2.30+-x64-linux.tar.gz
  url: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.2.30+-x64-linux.tar.gz

build:
    number: 1

requirements:
    build:
      - gcc

    run:
      - libgcc

about:
    home: http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastDocs
    license: Public Domain

