package:
  name: libsigcpp
  version: "2.99.8"

source:
  url: http://ftp.acc.umu.se/pub/gnome/sources/libsigc++/2.99/libsigc++-2.99.8.tar.xz 
  md5: 992654e072a253489bbe0d30495915bd
  fn: libsigc++-2.99.8.tar.xz

build:
  number: 3
 
requirements:
  build:
    - m4
    - automake
    - autoconf
    - libtool
    - pkg-config
    - gcc
    - perl 5.22.2.*
  run:
    - libgcc
    - perl 5.22.2.*

about:
  home: libsigc.sourceforge.net
  license: GPL
  summary: "libsigc++ implements a typesafe callback system for standard C++."
