package:
    name: boost-python
    version: 1.57.0

source:
   fn: boost_1_57_0.tar.bz2
   url: http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.bz2

build:
    number: 1

requirements:
    build:
      - gcc
      - bzip2
      - python

    run:
      - libgcc
      - bzip2
      - python

about:
    home: http://www.boost.org/
    license: Boost-1.0

