package:
  name: samtools
  version: "1.2"

source:
  fn: samtools-1.2.tar.bz2
  url: https://github.com/samtools/samtools/releases/download/1.2/samtools-1.2.tar.bz2

build:
  number: 2
  
requirements:
  build:
    - system
    - zlib
    - ncurses
    - gcc
  run:
    - system
    - zlib
    - ncurses

about:
  home: https://github.com/samtools/samtools
  summary: Tools (written in C using htslib) for manipulating next-generation sequencing data.
