{% set version = "0.3.106" %}

package:
  name: "aio"
  version: {{ version }}

build:
  number: 2

source:
  fn: libaio-{{ version }}-5.src.rpm
  url: http://vault.centos.org/5.11/os/SRPMS/libaio-{{ version }}-5.src.rpm 
  md5: 5ca835febe7b2e88363dabb551d50f30 

about:
  home: http://vault.centos.org/5.11/os/SRPMS/libaio-{{ version }}-5.src.rpm 
  summary: The Linux-native asynchronous I/O facility ("async I/O", or "aio") has a
           richer API and capability set than the simple POSIX async I/O facility.
           This library, libaio, provides the Linux-native API for async I/O.
           The POSIX async I/O facility requires this library in order to provide
           kernel-accelerated async I/O capabilities, as do applications which
           require the Linux-native async I/O API. 
  license: LGPL

