package:
  name: bcftools
  version: "1.2"

source:
  fn: bcftools-1.2.tar.bz2
  url: https://github.com/samtools/bcftools/releases/download/1.2/bcftools-1.2.tar.bz2

build:
  number: 1
  
requirements:
  build:
    - system
    - zlib
    - gcc
  run:
    - system
    - zlib

about:
  home: https://github.com/samtools/bcftools
  summary: This is the official development repository for BCFtools. 
