package:
  name: spyder
  version: 2.3.5dev

source:
  git_url: git@github.com:spyder-ide/spyder.git

build:
  osx_is_app: True

requirements:
  build:
    - python
    - sphinx
  run:
    - python
    - pyzmq
    - ipython
    - rope
    - pyflakes
    - pygments
    - jinja2
    - sphinx
    - pep8
    - pylint
    - pyqt
    - python.app      [osx]

test:
  commands:
    - spyder -h
  imports:
    - spyderlib

about:
  home: http://code.google.com/p/spyderlib/
  license: MIT
