package:
  name: gtk
  version: "3.16.6"

source:
  url: http://ftp.gnome.org/pub/gnome/sources/gtk+/3.16/gtk+-3.16.6.tar.xz 
  fn: gtk+-3.16.6.tar.xz

build:
  number: 2

requirements:
  build:
    #- gcc
    - python ==2.7.10
    - m4
    - autoconf
    - automake
    - pkg-config
    - libtool
    - system
    - glib
    - atk
    - pango
    - cairo
    - gdk-pixbuf
    - gobject-introspection
    - fontconfig
    - libepoxy
    - atk
    - dbus
    - dbus-glib
    - at-spi2-atk
  run:
    - system
    - glib
    - atk
    - pango
    - cairo
    - gdk-pixbuf
    - gobject-introspection
    - fontconfig
    - libepoxy
    - atk
    - dbus
    - dbus-glib
    - at-spi2-atk

about:
  home: http://www.gtk.org/

