package:
  name: gtk
  version: "3.91.0"

source:
  url: http://ftp.acc.umu.se/pub/GNOME/sources/gtk+/3.91/gtk+-3.91.0.tar.xz 
  fn: gtk+-3.91.0.tar.xz  

build:
  number: 4

requirements:
  build:
    - gcc
    - python ==2.7.13
    - m4
    - autoconf
    - automake
    - pkg-config
    - libtool
    - system
    - glib
    - atk
    - pango
    - cairo
    - gdk-pixbuf
    - gobject-introspection
    - fontconfig
    - libepoxy
    - atk
    - dbus
    - dbus-glib
    - at-spi2-atk
  run:
    - system
    - glib
    - atk
    - pango
    - cairo
    - gdk-pixbuf
    - gobject-introspection
    - fontconfig
    - libepoxy
    - atk
    - dbus
    - dbus-glib
    - at-spi2-atk

about:
  home: http://www.gtk.org/

