package:
  name: mpfr
  version: "3.1.3"

source:
  url: http://www.mpfr.org/mpfr-current/mpfr-3.1.3.tar.xz
  fn: mpfr-3.1.3.tar.xz

build:
  number: 1

requirements:
  build:
    - system
    - gmp
  run:
    - system
    - gmp

about:
  home: http://www.mpfr.org/
  summary: 'The GNU Multiple Precision Arithmetic Library'
