package:
  name: libepoxy
  version: "1.3.1"

source:
  url: https://github.com/anholt/libepoxy/releases/download/v1.3.1/libepoxy-1.3.1.tar.bz2 
  md5: 96f6620a9b005a503e7b44b0b528287d
  fn: libepoxy-1.3.1.tar.bz2

build:
  number: 1

requirements:
  build:
    - gcc
    - m4
    - autoconf
    - automake
    - pkg-config
    - libtool
    - system
  run:
    - system

about:
  home: https://github.com/anholt/libepoxy
  license: MIT
  summary: "Epoxy is a library for handling OpenGL function pointer management for you." 

