package:
  name: byobu
  version: "5.105"

source:
  fn: byobu_5.105.orig.tar.gz 
  url: https://launchpad.net/byobu/trunk/5.105/+download/byobu_5.105.orig.tar.gz 
  md5: 9a3c8fdd6cc2e7d01f276e582f8f6fe9

build:
  number: 1
  skip: True # [osx]

requirements:
  build:
    - newt
    - ncurses
    - libevent
    - tmux
  run:
    - newt
    - ncurses
    - libevent
    - tmux

test:
  commands:
    - byobu -c "echo 'hello world'"

about:
  home: http://byobu.co/
  license: GPLv3
  summary: Byobu is a GPLv3 open source text-based window manager and terminal multiplexer.

