package:
  name: knot
  version: "1.0.0"


source:
  fn: KNOT-1.0.0.tgz
  url: http://mathbio.nimr.mrc.ac.uk/download/KNOT/KNOT-1.0.0.tgz
  md5: 2556876109bae506fe171a45902db0b6


build:
  number: 2


requirements:
  build:
    - gcc

  run:


test:
  requires: 
    - knot

  commands:
    - which knot


about:
  home: http://mathbio.nimr.mrc.ac.uk/wiki/Software#KNOT
  summary: Detection of knots in protein folds.
