package:
  name: modeller
  version: 9.14

source:
  fn: modeller-9.14.tar.gz
  url: https://salilab.org/modeller/9.14/modeller-9.14.tar.gz

build:
  number: 3

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - _modeller
    - modeller
  commands:
    - python -c 'from modeller import *'
 
about:
  home: https://salilab.org/modeller/
  license: Proprietary
