package:
  name: mysql
  version: "5.6.24"

source:
  fn: mysql-5.6.24-linux-glibc2.5-x86_64.tar.gz [linux]
  url: http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.24-linux-glibc2.5-x86_64.tar.gz [linux]
  md5: f8a315a95db77cbc334a2869e4af87a0

build:
  number: 1

requirements:
  build:
    - system [linux]

about:
  home: http://www.mysql.com
  license: GPL

# vim:set ts=8 sw=2 sts=2 tw=78 et:
