package:
  name: mysqlclient
  version: "1.3.7"

source:
  git_url: https://github.com/PyMySQL/mysqlclient-python.git

build:
  number: 1

requirements:
  build:
    - python
    - zlib
    - openssl
    - mysql ==5.6.24
  run:
    - python
    - zlib
    - openssl
    - mysql ==5.6.24

test:
  requires:
    - mysql ==5.6.24
  imports:
    - MySQLdb
    - _mysql

about:
  home: https://github.com/PyMySQL/mysqlclient-python
  license: GNU General Public License (GPL)
  summary: 'Python interface to MySQL'
