{% set version = "5.7.17" %}

package:
  name: mysql
  version: {{ version }}

source:
  fn: mysql-{{ version }}-linux-glibc2.5-x86_64.tar.gz
  url: https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-{{ version }}-linux-glibc2.5-x86_64.tar.gz 
  md5: 699aeb2ad680d178171fa95a7ba7b347

build:
  number: 0
  # detect_binary_files_with_prefix: true

requirements:
  build:
    - unixodbc
#     # - gcc
#     - cmake
#     - bison
#     - ncurses
#     - zlib
#     - lzo
#     - jemalloc ==3.6.0
#     - aio
#     - readline
#     - openssl
#     - zeromq
#     - libxml2
    
  run:
    - unixodbc
    - aio
#     - libgcc
#     - ncurses ==5.9
#     - zlib
#     - lzo
#     - jemalloc ==3.6.0
#     - readline
#     - openssl
#     - zeromq 
#     - libxml2

test:
  commands:
    - mysql --help
    - mysqld --help
    # - [[ -e "$PATH/lib/plugin/connect.so" ]]

about:
  home: https://dev.mysql.com
  summary: MySQL Community Edition is a freely downloadable version of the world's most popular open source database that is supported by an active community of open source developers and enthusiasts. 
  license: GPL

