package:
  name: at-spi2-core
  version: "2.16.0"

source:
  url: http://ftp.gnome.org/pub/gnome/sources/at-spi2-core/2.16/at-spi2-core-2.16.0.tar.xz 
  md5: be6eeea370f913b7639b609913b2cf02
  fn: at-spi2-core-2.16.0.tar.xz

build:
  number: 1

requirements:
  build:
    # - gcc
    - python ==2.7.10
    - m4
    - autoconf
    - automake
    - libtool
    - pkg-config
    - system
    - glib
    - gobject-introspection
    - atk
    - dbus
    - dbus-glib
  run:
    - system
    - glib
    - gobject-introspection
    - atk
    - dbus
    - dbus-glib

about:
  home: http://www.linuxfromscratch.org/blfs/view/svn/x/atk.html
  summary: "ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications."

