package:
  name: uniconvertor
  version: "1.1.5"

source:
  fn: uniconvertor-1.1.5.tar.gz
  url: http://sk1project.org/dc.php?target=uniconvertor-1.1.5.tar.gz

requirements:
  build:
    - python
    - sk1libs
  run:
    - python
    - sk1libs
