package:
  name: pygobject
  version: "3.17.1"

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/pygobject/3.17/pygobject-3.17.1.tar.xz 
  fn: pygobject-3.17.1.tar.xz

build:
  number: 1

requirements:
  build:
    - m4
    - autoconf
    - automake
    - pkg-config
    - libtool
    - gcc
    - python
    - gnome-common
    - glib >=2.43 # [not win]
    - gobject-introspection
    - gettext
    - cairo
    - cairo-gobject
    - pycairo
    - libsigcpp
  run:
    - python
    - gnome-common
    - glib >=2.43 # [not win]
    - gobject-introspection 
    - gettext
    - cairo
    - cairo-gobject
    - pycairo
    - libsigcpp
test:
  imports:
    - gi
    - gi.repository
    - gi.repository.GObject
    - gi.repository.GLib
    - gi.repository.Gio
    - gi.repository.Gtk

about:
  home: https://wiki.gnome.org/Projects/PyGObject 
  license: LGPL 2.1
  summary: 'PyGObject is a Python extension module that gives clean and consistent access to the entire GNOME software platform through the use of GObject Introspection.'

