package:
  name: libxext
  version: 1.3.3

source:
  git_url: http://anongit.freedesktop.org/git/xorg/lib/libXext.git

build:
  number: 1
 
requirements:
  build:
    - system
    - gcc
    - m4
    - autoconf
    - automake
    - libtool
    - pkg-config
    - util-macros
    - python
    - xproto
    - libx11
    - xextproto
  run:
    - xproto
    - libx11
    - xextproto

about:
  home: 'http://cgit.freedesktop.org/xorg/lib/libXext/'
