package:
  name: autoheader
  version: "0.0.0.2"

source:
  url: http://iweb.dl.sourceforge.net/project/autoheader/0.0.0.2/autoheader-0.0.0.2.tar.bz2 
  fn: autoheader-0.0.0.2.tar.bz2

build:
  number: 1

requirements:
  build:
    - system
    - gcc
    - m4
    - autoconf
    - automake
  run:
    - system

about:
  home: http://sourceforge.net/projects/autoheader/ 
  license: GNU
  summary: "Creates template header files for use within configure scripts."
