package:
  name: snpEff
  version: "4.1g"

source:
  fn: snpEff_latest_core.zip
  url: http://iweb.dl.sourceforge.net/project/snpeff/snpEff_latest_core.zip

build:
  number: 1
  
requirements:
  build:
    - system
    - gcc
  run:
    - system

about:
  home: http://snpeff.sourceforge.net/index.html
  summary: Genetic variant annotation and effect prediction toolbox. 
