package:
  name: mysqlclient
  version: "1.3.9"

source:
  fn: mysqlclient-1.3.9.tar.gz
  url: https://pypi.python.org/packages/db/f5/c8e1657985c31dda16e434edf5257c31572fa5faacd7e48b1618390e4b18/mysqlclient-1.3.9.tar.gz
  md5: a9df2961f4664bfd4b9dac50d7b28048

build:
  number: 2

requirements:
  build:
    - python
    - mysql
    # - mysql-connector-c
  run:
    - python
    - mysql
    # - mysql-connector-c

test:
  requires:
    - pandas
    - sqlalchemy
  imports:
    - MySQLdb

about:
  home: https://github.com/PyMySQL/mysqlclient-python
  license: GPL 
  summary: 'Python interface to MySQL'

