package:
  name: harfbuzz
  version: "1.0.1"

source:
  url: http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.0.1.tar.bz2 
  fn: harfbuzz-1.0.1.tar.bz2

build:
  number: 3

requirements:
  build:
    - m4
    - autoconf
    - automake
    - libtool
    - pkg-config
    - gcc
    - glib
    - icu 
    - libffi
    - freetype
  run:
    - libgcc
    - glib
    - icu 
    - libffi
    - freetype

about:
  home: http://www.freedesktop.org/wiki/Software/HarfBuzz/ 
  summary: "HarfBuzz is an OpenType text shaping engine."

