package:
  name: doxygen
  version: 1.8.10

source:
  git_url: https://github.com/doxygen/doxygen.git 

requirements:
  build:
    - gcc
    - system
    - m4
    - autoconf
    - automake
    - libtool
    - pkg-config
    - cmake
    - flex
    - bison 
  run:
    - system

about:
  home: 'http://www.stack.nl/~dimitri/doxygen/index.html'
