package:
  name: cairomm
  version: "1.10.0"

source:
  url: http://cairographics.org/releases/cairomm-1.10.0.tar.gz 
  md5: 9c63fb1c04c8ecd3c5e6473075b8c39f
  fn: cairomm-1.10.0.tar.gz

build:
  number: 2

requirements:
  build:
    - m4
    - autoconf
    - automake
    - libtool
    - pkg-config
    - gcc
    - boost
    - mm-common
    - cairo
    - libsigcpp
    - freetype
    - pthread-stubs
  run:
    - libgcc
    - boost
    - mm-common
    - cairo
    - libsigcpp
    - freetype
    - pthread-stubs

about:
  summary: 'A C++ API for cairo'

