package:
  name: poppler
  version: "0.34.0"

source:
  url: http://poppler.freedesktop.org/poppler-0.34.0.tar.xz 
  fn: poppler-0.34.0.tar.xz

build:
  number: 1

requirements:
  build:
    - autoconf
    - automake
    - libtool
    - m4
    - pkg-config
    - gcc
  run:

about:
  home: http://poppler.freedesktop.org/
  summary: "Poppler is a PDF rendering library based on the xpdf-3.0 code base."

