package:
    name: boost-python
    version: 1.58.0

source:
   fn: boost_1_58_0.tar.bz2
   url: http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2

build:
    number: 0

requirements:
    build:
      - gcc
      - python

    run:
      - libgcc
      - python

about:
    home: http://www.boost.org/
    license: Boost-1.0
