package:
  name: libxrender
  version: 0.9.8

source:
  git_url: http://anongit.freedesktop.org/git/xorg/lib/libXrender.git

build:
  number: 2

requirements:
  build:
    - m4
    - pkg-config
    - automake
    - autoconf
    - libtool
    - gcc
    - util-macros
    - libx11
    - renderproto
  run:
    - libx11
    - renderproto

about:
  home: 'http://cgit.freedesktop.org/xorg/lib/libXrender/'
  license:
  summary: 
